### ISSUE TITLE
Use a tagged version of Browsershot

### ISSUE THREAD

**Issue by freekmurze** [murrion/php_post_to_linkedin#1]
You're using the dev-master version of Browsershot. I'll be making some breaking changes to that package soon. If you want to avoid problems you should use a tagged version of the package.

(fyi: I've mentioned your blogpost in the README of Browsershot)

**Comment by ghost** [comment]
Hi, Cool, I will change it to use 1.1.0 so instead. Thank you for the heads-up on future changes.

Also, a very big thank you for adding a reference to this on your Readme file too.

**Comment by ghost** [comment]
composer file updated now.
